### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [HugoJourdan/Color-Flow#5]
I got this from a user:
```
Details:
Traceback (most recent call last):

  File "vanillaBase.py", line 507, in action_
    self.callback(sender)

  File "plugin.py", line 419, in CheckBox_Callback
    self.font.userData["com.hugojourdan.ColorFlow-master-data"][selectedMasterID][color] = 1

TypeError: string indices must be integers
```

**Comment by HugoJourdan** [comment]
Can't replicate this issue.
Solved
